# -*- coding: utf-8 -*-
"""The Celebrity Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9tOSAIZe5NPkhKOumPXrVtSmgmxKZlQ
"""

N = 4
M = [[0,1,1,0],
     [0,0,0,0],
     [0,1,0,0],
     [0,1,1,0]]
for i in range(len(M)):
  for j in range(len(M[i])):
    print(M[i][j], end=" ")
  print()

Dict = {}
for i in range(len(M)):
  for j in range(len(M[i])):
    # everyone knows itself, so i and j should not be equal
    if (i != j):
      # i should know j, but j should not know i
      if (M[i][j] == 1 and M[j][i] != 1):
        if j in Dict.keys():
          # Incrementing counter of people knowing j
          Dict[j] = Dict[j]+1
        else:
          Dict[j] = 1

max_value = 0
if Dict:
  # finding max value for a person
  max_value = max(Dict.values())
print(max_value)
print(Dict)
if (max_value == len(M)-1):
  # index of person, who is known by all people in party
  max_key = max(Dict, key=Dict.get)
  print(max_key)
else:
  print(-1)